language: scala

# only trigger builds on master
branches:
  only:
    - master
    - v2.1.x
    - v2.2.x

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage test coverageReport coverageAggregate codacyCoverage

scala:
   - 2.10.6
   - 2.11.12
   - 2.12.7

before_install:
    - pip install --user codecov

after_success:
  - codecov

jdk:
  - oraclejdk8
